version: 2
jobs:
  build:
    working_directory: ~/AngularCircleCI
    parallelism: 1
    shell: /bin/bash --login
    docker:
          - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: mkdir -p /tmp/circleci-artifacts
      - run: mkdir -p /tmp/circleci-test-results
      - run: ls *
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: npm start
          background: true
      - run: sleep 5
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run protractor
      - store_test_results:
           path: /tmp/circleci-test-results
      - store_artifacts:
           path: /tmp/circleci-test-results