version: 2
jobs:
  build:
    working_directory: ~/AngularCircleCI
    parallelism: 1
    shell: /bin/bash --login
    docker:
          - image: buildpack-deps:bionic
    steps:
      - checkout
      - run: mkdir -p ~/AngularCircleCI/circleci-artifacts
      - run: mkdir -p ~/AngularCircleCI/circleci-test-results
      - run:
          working_directory: ~/AngularCircleCI
          command: 'curl -sL https://deb.nodesource.com/setup_8.x | bash -; apt-get install -y nodejs; nodejs --version; '
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: npm start
          background: true
      - run: sleep 5
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run protractor
      - store_test_results:
           path: ~/AngularCircleCI/circleci-test-results
      - store_artifacts:
           path: ~/AngularCircleCI/circleci-test-results